version: '3.9'
services:
  board-db:
    env_file:
      - ./.env
    image: 'postgres:14.3'
    volumes:
      - board-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  miniboard-backend:
    build: .
    env_file:
      - ./env
    ports:
      - 3333:3333
volumes:
  board-db-data:
    driver: local
