version: '3.9'
services:
  main-db:
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${MAIN_DB_USERNAME}
      - POSTGRES_PASSWORD=${MAIN_DB_PASSWORD}
      - POSTGRES_DB=${MAIN_DB_DATABASE}
    image: 'postgres:14.3'
    volumes:
      - main-db-data:/var/lib/postgresql/data
    ports:
      - ${MAIN_DB_PORT}:5432
  main-backend:
    build: .
    env_file:
      - .env
    ports:
      - ${BACKEND_HTTP_PORT}:${BACKEND_HTTP_PORT}
volumes:
  main-db-data:
    driver: local
